---
title: "r_data_types"
author: "Ruth Enriquez"
format: html
editor: visual
---

## Create some data, check the classes, index!

Vectors, lists & data frames

In your Quarto document:

1.  Create a vector called vec_1 containing the following

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)

#Checking the data
class(vec_1)
typeof(vec_1)

#Access elements

vec_1_e3 <- vec_1[3]
vec_1_e1 <- vec_1[1]
vec_1_e5to7 <- vec_1[5:7]

#Reassign vec_1
vec_1_char <- as.character(vec_1)

vec_1_char

```

```{r}
#Create vector called vec_2

vec_2 <- c(town = "Santa Barbara",
           location ="Rincon",
           swell = "south")
class(vec_2)

#What is the length of vec_2
length(vec_2)

#Access 2nd element by name & store as vec_2_e2
vec_2_e2 <- vec_2[2]
```

Create a data frame called df_1

```{r}
region <- c("A", "B", "A", "D")
species <- c("otter", "great white", "sea lion", "gray whale")
count <- c(12, 2, 36, 6)

df_1 <- data.frame(region, species, count)

#check data frame class
class(df_1)

#check species column class
class(df_1$species)

#Find the maximum value of the count() column, store as max_count
max_count <- max(df_1$count)
```
